-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES: Stores user preferences and sync status
create table profiles (
  id uuid references auth.users not null primary key, -- Linked to Supabase Auth (we might need to link to MSAL ID differently if not using Supabase Auth, but let's assume we map it)
  -- Wait, we are using MSAL for auth. So we might not have a Supabase User ID if we don't use Supabase Auth.
  -- Strategy: We'll use the Microsoft 'oid' (Object ID) as the primary key or a unique column.
  -- Let's stick effectively to "Custom Auth" concept or just trust the client for V1 (insecure but fast) 
  -- OR better: We treat the 'email' as the primary identifier for simplicity in this prototype.
  email text unique not null,
  display_name text,
  humane_start_local time default '09:00',
  humane_end_local time default '17:00',
  timezone TEXT,
  humane_start_local TEXT, -- Legacy (keep for fallback)
  humane_end_local TEXT,   -- Legacy (keep for fallback)
  humane_windows JSONB DEFAULT '[]'::jsonb, -- New Multi-Window Support
  last_synced_at TIMESTAMPTZ
);

-- GROUPS: Shared spaces
create table groups (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  invite_code text unique default substr(md5(random()::text), 0, 7),
  created_at timestamptz default now()
);

-- GROUP MEMBERS: Who is in what group
create table group_members (
  group_id uuid references groups(id) on delete cascade,
  profile_email text references profiles(email) on delete cascade,
  primary key (group_id, profile_email)
);

-- AVAILABILITY CACHE: The simple "Busy" slots
create table availability_cache (
  id bigint generated by default as identity primary key,
  profile_email text references profiles(email) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  created_at timestamptz default now()
);

-- RLS (Row Level Security) - Simplified for Prototype
-- Real production would need signed JWTs from MSAL exchanged for Supabase Tokens, or custom claims.
-- For this "Friend Prototype", we will enable public read/write for verified emails (client-side trust).
-- WARNING: Not for enterprise production.
alter table profiles enable row level security;
alter table groups enable row level security;
alter table group_members enable row level security;
alter table availability_cache enable row level security;

-- Policies (Open for Demo/Prototype)
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (true);
create policy "Users can update their own profile" on profiles for update using (true);

create policy "Groups are viewable by everyone" on groups for select using (true);
create policy "Anyone can create groups" on groups for insert with check (true);

create policy "Members are viewable by everyone" on group_members for select using (true);
create policy "Anyone can join groups" on group_members for insert with check (true);

create policy "Availability is viewable by everyone" on availability_cache for select using (true);
create policy "Anyone can insert availability" on availability_cache for insert with check (true);
-- Note: In a real app, successful MSAL login would generate a Supabase JWT to enforce "Can only edit MY rows".
