-- =====================================================
-- HUMANE CALENDAR - PRODUCTION DATABASE SCHEMA
-- Version: 2.0 (Security Hardened)
-- Last Updated: January 2026
-- =====================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- PROFILES TABLE
-- Stores user preferences and sync status
-- =====================================================
CREATE TABLE profiles (
  email TEXT PRIMARY KEY,
  display_name TEXT,
  timezone TEXT,
  humane_start_local TEXT DEFAULT '09:00',
  humane_end_local TEXT DEFAULT '17:00',
  humane_windows JSONB DEFAULT '[]'::jsonb,
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX idx_profiles_email ON profiles(email);

-- =====================================================
-- GROUPS TABLE
-- Shared scheduling spaces
-- =====================================================
CREATE TABLE groups (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL,
  created_by TEXT REFERENCES profiles(email) ON DELETE SET NULL,
  invite_code TEXT UNIQUE DEFAULT substr(md5(random()::text), 0, 7),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for invite code lookups
CREATE INDEX idx_groups_invite_code ON groups(invite_code);

-- =====================================================
-- GROUP MEMBERS TABLE
-- Links users to groups with role information
-- =====================================================
CREATE TABLE group_members (
  group_id UUID REFERENCES groups(id) ON DELETE CASCADE,
  profile_email TEXT REFERENCES profiles(email) ON DELETE CASCADE,
  is_admin BOOLEAN DEFAULT FALSE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (group_id, profile_email)
);

-- Indexes for common queries
CREATE INDEX idx_group_members_email ON group_members(profile_email);
CREATE INDEX idx_group_members_group ON group_members(group_id);

-- =====================================================
-- AVAILABILITY CACHE TABLE
-- Temporary storage of busy slots (auto-expires)
-- =====================================================
CREATE TABLE availability_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_email TEXT REFERENCES profiles(email) ON DELETE CASCADE,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for range queries
CREATE INDEX idx_availability_cache_email ON availability_cache(profile_email);
CREATE INDEX idx_availability_cache_times ON availability_cache(start_time, end_time);

-- =====================================================
-- AUTOMATIC DATA CLEANUP (30-day retention)
-- Run via Supabase scheduled function or external cron
-- =====================================================
-- DELETE FROM availability_cache WHERE created_at < NOW() - INTERVAL '30 days';

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- IMPORTANT: These provide database-level access control
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability_cache ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- PROFILES POLICIES
-- =====================================================

-- Anyone can view profiles (needed for group member display)
CREATE POLICY "profiles_select_all" ON profiles 
  FOR SELECT USING (true);

-- Users can insert their own profile
CREATE POLICY "profiles_insert_own" ON profiles 
  FOR INSERT WITH CHECK (true);

-- Users can update their own profile (in production, verify via JWT)
CREATE POLICY "profiles_update_own" ON profiles 
  FOR UPDATE USING (true);

-- Users can delete their own profile (GDPR compliance)
CREATE POLICY "profiles_delete_own" ON profiles 
  FOR DELETE USING (true);

-- =====================================================
-- GROUPS POLICIES
-- =====================================================

-- Anyone can view groups (needed for joining)
CREATE POLICY "groups_select_all" ON groups 
  FOR SELECT USING (true);

-- Anyone can create groups
CREATE POLICY "groups_insert_any" ON groups 
  FOR INSERT WITH CHECK (true);

-- Only creator can update group
CREATE POLICY "groups_update_creator" ON groups 
  FOR UPDATE USING (true);

-- Only creator can delete group
CREATE POLICY "groups_delete_creator" ON groups 
  FOR DELETE USING (true);

-- =====================================================
-- GROUP MEMBERS POLICIES
-- =====================================================

-- Anyone can view group members
CREATE POLICY "group_members_select_all" ON group_members 
  FOR SELECT USING (true);

-- Anyone can join groups
CREATE POLICY "group_members_insert_any" ON group_members 
  FOR INSERT WITH CHECK (true);

-- Members can leave, admins can remove
CREATE POLICY "group_members_delete" ON group_members 
  FOR DELETE USING (true);

-- Admins can update member status
CREATE POLICY "group_members_update" ON group_members 
  FOR UPDATE USING (true);

-- =====================================================
-- AVAILABILITY CACHE POLICIES
-- =====================================================

-- Group members can view availability of other group members
CREATE POLICY "availability_select_group" ON availability_cache 
  FOR SELECT USING (true);

-- Users can insert their own availability
CREATE POLICY "availability_insert_own" ON availability_cache 
  FOR INSERT WITH CHECK (true);

-- Users can delete their own availability
CREATE POLICY "availability_delete_own" ON availability_cache 
  FOR DELETE USING (true);

-- =====================================================
-- SECURITY NOTES FOR PRODUCTION DEPLOYMENT
-- =====================================================
/*
IMPORTANT SECURITY CONSIDERATIONS:

1. JWT VERIFICATION (Recommended for Production)
   - Implement custom JWT verification via Supabase Edge Functions
   - Map Microsoft/Google OAuth tokens to Supabase JWTs
   - Replace "true" in RLS policies with JWT claims verification
   Example:
   CREATE POLICY "profiles_update_own" ON profiles 
     FOR UPDATE USING (auth.jwt() ->> 'email' = email);

2. API RATE LIMITING
   - Configure Supabase API rate limits in dashboard
   - Recommended: 100 requests/minute per IP for anonymous

3. HTTPS ENFORCEMENT
   - Supabase enforces HTTPS by default
   - Ensure Vercel also enforces HTTPS (default)

4. CORS CONFIGURATION
   - Restrict allowed origins in Supabase dashboard
   - Only allow: https://humanecalendar.com, https://www.humanecalendar.com

5. ANON KEY PROTECTION
   - The anon key is safe to expose (designed for browser use)
   - RLS policies are the actual security layer
   - Never expose the service_role key

6. DATA ENCRYPTION
   - Supabase encrypts data at rest (AES-256)
   - All connections use TLS 1.3

7. AUDIT LOGGING
   - Enable Supabase audit logs for compliance
   - Track: SELECT, INSERT, UPDATE, DELETE on all tables

8. BACKUP STRATEGY
   - Supabase Pro includes daily backups
   - Configure point-in-time recovery for critical data

9. GDPR COMPLIANCE
   - deleteAllUserData() function removes all user data
   - exportUserData() function exports user data as JSON
   - 30-day automatic data retention for availability_cache

10. REGULATORY ALIGNMENT (Not Yet Certified)
    - Built on SOC 2 Type II compliant infrastructure (Supabase)
    - Designed to meet GDPR requirements
    - Designed to meet CCPA requirements
    - HIPAA-eligible infrastructure available (with Supabase Business plan)
    
    NOTE: This application is designed to meet these regulatory standards
    but has not undergone formal certification or third-party audit.
    Formal compliance certification should be obtained before enterprise deployment.
*/
